### ISSUE TITLE
Cannot set property localStorage of #<Window> which has only a getter 

### ISSUE THREAD

**Issue by weisssean** [KaiSforza/mock-local-storage#17]
I updated my webpack and babel to the latest version and since the update I cannot set the local storage or session storage.

When running:
`window.localStorage = global.localStorage;`
or: 
`window.sessionStorage = global.sessionStorage;`
it throws:
`TypeError: Cannot set property sessionStorage of #<Window> which has only a getter`

**Comment by weisssean** [comment]
Found a workaround:
Instead of
`window.localStorage = global.localStorage;`

I used:
`Object.defineProperty(window, 'localStorage', { value: global.localStorage,configurable:true,enumerable:true,writable:true });`

**Comment by nikolay-turpitko** [comment]
@weisssean It'd be great if you could to create a PR to fix or better document it with some tests to reproduce it, preferably.

**Comment by KaiSforza** [comment]
@weisssean Just checking in if this is still an issue or if you are still using this solution.

**Comment by weisssean** [comment]
It's used in code I don't have access to anymore, sorry.

**Comment by KaiSforza** [comment]
Ah, okay. I'll close this for now. If anyone else has run into this, feel free to [open an issue on gitlab](https://gitlab.com/kaictl/node/mock-local-storage/-/issues/new).
